mep = {'Lars ADAKTUSSON': '@Ladaktusson',
 'Isabella ADINOLFI': '@Isa_Adinolfi',
 'Laura AGEA': '@AgeaLaura',
 'Clara Eugenia AGUILERA GARCÍA': '@ClaraAguilera7',
 'Tim AKER': '@Tim_Aker',
 'Marina ALBIOL GUZMÁN': '@MarinaAlbiol',
 'Jan Philipp ALBRECHT': '@JanAlbrecht',
 'Louis ALIOT': '@louis_aliot',
 'Michèle ALLIOT-MARIE': '@MAlliotMarie',
 'Lucy ANDERSON': '@LucyAndersonMEP',
 'Max ANDERSSON': '@MaxAndersson',
 'Eric ANDRIEU': '@Eric_Andrieu',
 'Laima Liucija ANDRIKIENĖ': '@Andrikiene',
 'Nikos ANDROULAKIS': '@androulakisnick',
 'Gerolf ANNEMANS': '@gannemans',
 'Maria ARENA': '@Mariearenaps',
 'Pascal ARIMONT': '@PASCALARIMONT',
 'Marie-Christine ARNAUTU': '@MCArnautu',
 'Jonathan ARNOTT': '@JonathanArnott',
 'Jean ARTHUIS': '@JeanArthuis',
 'Richard ASHWORTH': '@RichardAshMEP',
 'Janice ATKINSON': '@JaniceUKIP',
 'Margrete AUKEN': '@MargreteAuken',
 'Petras AUŠTREVIČIUS': '@petras_petras',
 'Inés AYALA SENDER': '@IAyalaSender',
 'Pilar AYUSO': '@ayuso_pilar',
 'Johannes Cornelis van BAALEN': '@hansvanbaalen',
 'Guillaume BALAS': '@BalasGuillaume',
 'Zigmantas BALČYTIS': '@balcytis',
 'Amjad BASHIR': '@AmjadBashirMEP',
 'Gerard BATTEN': '@GerardBattenMEP',
 'Nicolas BAY': '@nicolasbayfn',
 'Hugues BAYET': '@HuguesBayet',
 'Catherine BEARDER': '@catherinemep',
 'Beatriz BECERRA BASTERRECHEA': '@beatrizbecerrab',
 'Tiziana BEGHIN': '@beghin_t',
 'Bas BELDER': '@BasBelderMEP',
 'Bendt BENDTSEN': '@BendtEU',
 'Brando Benifei': '@brandobenifei',
 'Xabier Benito': '@xabierbenito',
 'Pervence Beres': '@pervencheberes',
 'Joelle Bergeron': '@jbergeronmep',
 'Goffredo Maria Bettini': '@goffredobettini',
 'Izaskun Bilbao Barandica': '@IzaskunBilbaoB',
 'Dominique Bilde': '@dominiquebilde',
 'Mira Bizzotto': '@marabizzotto',
 'Malin Björk': '@malinBjork_EU',
 'Jose Blanco Lopez': '@pepeblancoEP',
 'Vilija Blinkeviciute': '@vilijablinkeviciute',
 'Franc Bogovic ': '@Franc_Bogovic',
 'Simona Bonafe': '@simonabonafe',
 'Michal Boni': '@MichalBoni',
 'David Borrelli': '@borrellidavid',
 'Biljana Borzan': '@biljanaborzan',
 'Victor Boştinaru': '@victorbostinaru',
 'Jose Bove ': '@josebove',
 'Lynn Boylen': '@LNBDublin',
 'Paul Brannen': '@paulbrannenne',
 'Mercedes Bresso': '@mercedesbresso',
 'Renata Briano': '@renatabriano',
 'Steeve Briois': '@steevebriois',
 'Elmar Brok': '@elmarbrok_MEP',
 'Klaus Buchner': '@Dr_KlausBuchner',
 'Daniel Buda': '@MEPDanielBuda',
 'Udo Bullmann': '@UdoBullmann',
 'Reinhard Bütıkofer': '@bueti',
 'Jerzy Buzek': '@JerzyBuzek',
 'Soledad Cabezon Ruiz': '@SoledadCabezon',
 'Alain Cadec': '@AlainCadec',
 'Enrique Calvet Chambon': '@EnriqueCalvet',
 'Wim van de Camp': '@WimvandeCamp',
 'David Campbell Bannerman': '@DCBMEP',
 'Nicola Caputo': '@NicolaCaputo',
 'Matt Carthy': '@mattcarthy',
 'James Carver': '@jamesjimcarver',
 'David Casa': '@DavidCasaMEP',
 'DAniel Caspary': '@caspary',
 'Fabio Massimo Castaldo': '@FMCastaldo',
 'Pilar del Castillo Vera': '@delcastillop',
 'Jean Marie Cavada': '@JeanMarieCavada',
 'Lorenzo Cesa': '@L_cesa',
 'Dita Charanzova': '@charanzova',
 'Aymeric Chauprade': '@a_chauprade',
 'Nessa Childers': '@NChildersMEP',
 'Caterina Chinnic': '@CaterinaChinnic',
 'Nikos Chountis': '@NikosChountis',
 'Ole Christensen': '@OleEU',
 'Lefteris Christoforou': '@LefChristoforou',
 'Kostas Chrysogonos': '@Chrysogonos_K',
 'Salvatore Cicu\u200f': '@SalvoCicu',
 'Angelo Ciocca': '@AngeloCiocca',
 'Alberto Cirio\u200f\xa0': '@Alberto_Cirio',
 'Deirdre Clune\u200f': '@DeirdreCluneMEP',
 'David Coburn\u200f\xa0': '@DavidCoburnUKip',
 'Carlos Coelho\u200f': '@CarlosCoelhoPE',
 'Sergio Cofferati\u200f\xa0': '@Cofferati',
 'Lara Comi': '@comilara',
 'Therese Comodini Cachia': '@ComodiniCachia',
 'Anna Maria Corazza B\u200fildt': '@AnnaMariaCB',
 'Richard Corbett': '@RCorbettMEP',
 'Ignazio Corrao': '@ignaziocorrao',
 'Silvia Costa\u200f': '@SilviaCostaEU',
 'Javier Couso Permuy': '@Caninator',
 'Andrea Cozzolino': '@cozzolino62',
 'Michael Cramer': '@MepMCramer',
 'Csáky Pál\u200f': '@csakypal',
 'Ryszard Czarnecki': '@r_czarnecki',
 'Edward Czesak': '@EdwardCzesak',
 'Peter van Dalen': '@petervdalen',
 'Miriam Dalli': '@Miriamdalli',
 'Daniel Dalton': '@ddalton40',
 'Jakob Dalunde': '@JakopDalunde',
 "Rosa D'amato": '@rosadamato634',
 'Seb Dance': '@SebDance',
 'Viorica Dancila': '@VioricaDancila',
 'Arnaud Danjean': '@ArnaudDanjean',
 'Nicola Danti\u200f': '@DantiNicola',
 'Michel Dantin': '@MichelDANTIN',
 'Rachida Dati': '@datirachida',
 'Paolo De Castro': '@paolodecastro',
 'Angélique Delahaye': '@Delahaye_Europe',
 'Andor Deli': '@AndorDeli',
 'Karima Delli\u200f': '@KarimaDelli',
 'Mady Delvaux': '@mady_delvaux',
 'Fabio De Masi\u200f': '@FabioDeMasi',
 'Mark Demesmaeker': '@markdemesmaeker',
 'Isabella De Monte': '@IsabellaDeMonte',
 'Jean-Paul DENANOT': '@jpdenanot',
 'Tamás DEUTSCH': '@dajcstomi',
 'Agustín DÍAZ DE MERA GARCÍA': '@ppegrupo',
 'Martina DLABAJOVÁ': '@Mdlabajova',
 'Anneliese DODDS': '@AnnelieseDodds',
 'Herbert DORFMANN': '@HerbertDorfmann',
 'Pascal DURAND': '@PDurandOfficiel',
 'Stefan ECK': '@Stefan_Eck_MEP',
 'Bas EICKHOUT': '@BasEickhout',
 'Linnéa ENGSTRÖM': '@LinneaEngstrom',
 'Cornelia ERNST': '@ErnstCornelia',
 'Ismail ERTUG': '@IsmailErtug',
 'Jill EVANS': '@JillEvansMEP',
 'Tanja FAJON': '@tfajon',
 'José Inácio FARIA': '@JoseFariaMEP',
 'Markus FERBER': '@MarkusFerber',
 'José Manuel FERNANDES': '@JMFernandesEU',
 'Jonás FERNÁNDEZ': '@jonasfernandez',
 'Laura FERRARA': '@LFerraraM5S',
 'Santiago FISAS AYXELÀ': '@SantiagoFisas',
 'Raffaele FITTO': '@RaffaeleFitto',
 'Christofer FJELLNER': '@Fjellner',
 'Luke Ming FLANAGAN': '@lukeming',
 'Monika FLAŠÍKOVÁ BEŇOVÁ': '@MonikaFlaBenova',
 'Knut FLECKENSTEIN': '@knufleckenstein',
 'Eleonora Forenza': '@eleonoraforenza',
 'Jacqueline FOSTER': '@jfostermep',
 'Lampros FOUNTOULIS': '@FountoulisLampr',
 'Ashley FOX': '@Ashleyfoxmep',
 'Eugen Freund': '@EugenAFreund',
 'Mariya Gabriel': '@GabrielMariya',
 'Michael GAHLER': '@michaelgahler',
 'Kinga GÁL': '@FideszEP',
 'Ildikó GÁLL-PELCZ': '@ildiko.pelcz.gall',
 'Francesc GAMBÚS': '@fgambus_eu',
 'Iratxe GARCÍA PÉREZ': '@IratxeGarper',
 'Eider GARDIAZABAL RUBIAL': '@EGardiazabal',
 'Elisabetta GARDINI': '@EGardini',
 'Enrico GASBARRA': '@enricogasbarra',
 'Jens GEIER': '@EuropaJens',
 'Elena GENTILA': '@elena_gentile',
 'Gerben-Jan GERBRANDY': '@Gerbrandy',
 'Arne GERICKE': '@Arne_Gericke',
 'Lidia Joanna GERINGER de OEDENBERG': '@lidiageringer',
 'Sven GIEGOLD': '@sven_giegold',
 'Adam GIEREK': '@AdamGierek',
 'Neena GILL': '@NeenaGmep',
 'Nathan GILL': '@NathanGillMEP',
 'María Teresa GIMÉNEZ BARBAT': '@gimenezbarbat',
 'Julie GIRLING': '@juliegirling',
 'Michela GIUFFRIDA': '@m_giuffrida',
 'Sylvie GODDYN': '@Sylvie_Goddyn',
 'Charles GOERENS': '@CharlesGoerens',
 'Bruno GOLLNISCH': '@brunogollnisch',
 'Ana GOMES': '@AnaGomesMEP',
 'Tania GONZÁLEZ PEÑAS': '@TaniaGonzalezPs',
 'Esteban GONZÁLEZ PONS': '@gonzalezpons',
 'Beata GOSIEWSKA': '@BeataGosiewska',
 'Marcel de GRAAFF': '@MJRLdeGraaff',
 'Giorgos GRAMMATIKAKIS': '@GrammatikakisG',
 'Maria GRAPINI': '@MariaGrapini',
 'Ingeborg GRÄSSLE': '@inge_graessle',
 'Karoline GRASWANDER-HAINZ': '@graswanderhainz',
 'Nathalie GRIESBECK': '@Nat_GRIESBECK',
 'Theresa GRIFFIN': '@theresag_eu',
 'Iveta GRIGULE': '@IvetaGrigule',
 'Françoise GROSSETÊTE': '@GrosseteteF',
 'Andrzej GRZYB': '@GrzybAndrzej',
 'Roberto GUALTIERI': '@gualtierieurope',
 'Sylvie GUILLAUME': '@sylvieguillaume',
 'Antanas GUOGA': '@TonyGuoga',
 'Jytte GUTELAND': '@JytteGuteland',
 'Sergio GUTIÉRREZ PRIETO': '@Sergio_GP',
 'Takis HADJIGEORGIOU': '@thadjigeorgiou',
 'Thomas HÄNDEL': '@thaendel',
 'Daniel HANNAN': '@DanielJHannan',
 'Marian HARKIN': '@MarianHarkin',
 'Rebecca HARMS': '@RebHarms',
 'Martin HÄUSLING': '@MartinHaeusling',
 'Heidi HAUTALA': '@HeidiHautala',
 'Brian HAYES': '@brianhayesMEP',
 'Anja HAZEKAMP': '@anjahazekamp',
 'Anna HEDH': '@AnnaHedh',
 'Roger HELMER': '@RogerHelmerMEP',
 'Hans Olaf HENKEL': '@HansOlafHenkel',
 'Krzysztof HETMAN': '@Hetman_K',
 'Maria HEUBUCH': '@MariaHeubuch',
 'Czesław HOC': '@czeslawhoc',
 'Monika HOHLMEIER': '@MHohlmeier',
 'Gunnar HÖKMARK': '@ghokmark',
 'Mary HONEYBALL': '@maryhoneyball',
 'Brice HORTEFEUX': '@BriceHortefeux',
 'Danuta Maria HÜBNER': '@danutahuebner',
 'Ian HUDGHTON': '@hudghtonmepSNP',
 'Jan HUITEMA': '@jhuitema',
 'Sophia VELD': '@SophieintVeld',
 'Carlos ITURGAIZ': '@carlositurgaiz',
 'Cătălin Sorin IVAN': '@Catalin_Ivan',
 'Liisa JAAKONSAARI': '@ljaakonsaari',
 'Anneli JÄÄTTEENMÄKI': '@jaatteenmaki',
 'Yannick JADOT': '@yjadot',
 'Peter JAHR': '@peter_jahr',
 'Ivan JAKOVČIĆ': '@IvanJakovcic',
 'Diane JAMES': '@DianeJamesMEP',
 'Ramón JÁUREGUI ATONDO': '@RJaureguiA',
 'Benedek JÁVOR': '@javorbenedek',
 'Danuta JAZŁOWIECKA': '@DJazlowiecka',
 'Petr JEŽEK': '@JezekCZ',
 'Teresa JIMÉNEZ BECERRIL BARRIO': '@TeresaJBecerril',
 'Eva JOLY': '@EvaJoly',
 'Dennis de JONG': '@DdJong',
 'Agnes JONGERIUS': '@a_jongerius',
 'Marc JOULAUD': '@MarcJoulaud',
 'Josu JUARISTI ABAUNZ': '@Josu_Juaristi',
 'Marek JUREK': '@marekjurek',
 'Philippe JUVIN': '@philippejuvin',
 'Karin KADENBACH': '@karinkadenbach',
 'Eva KAILI': '@EvaKaili',
 'Kaja KALLAS': '@kajakallas',
 'Sandra KALNIETE': '@Kalniete',
 'Syed KAMALL': '@SyedKamall',
 'Othmar KARAS': '@othmar_karas',
 'Rina Ronja KARI': '@rinakari',
 'Sajjad KARIM': '@SajjadKarimMEP',
 'Krišjānis KARIŅŠ': '@krisjaniskarins',
 'Sylvia-Yvonne KAUFMANN': '@KaufmannSylvia',
 'Manolis KEFALOGIANNIS': '@M_Kefalogiannis',
 'Ska KELLER': '@SkaKeller',
 'Seán KELLY': '@SeanKellyMEP',
 'Afzal KHAN': '@akhanmep',
 'Jude KIRTON-DARLING': '@Jude_KD',
 'Jeppe KOFOD': '@JeppeKofod',
 'Arndt KOHN': '@ArndtKohn',
 'Bernd KÖLMEL': '@Bernd_Koelmel',
 'Kateřina KONEČNÁ': '@Konecna_K',
 'Janusz KORWIN-MIKKE': '@korwinmikke',
 'Ádám KÓSA': '@adamkosamep',
 'Elisabeth KÖSTINGER': '@ElliKoestinger',
 'Stelios KOULOGLOU': '@SteliosKoul',
 'Peter KOUROUMBASHEV': '@PKouroumbashev',
 'Andrey KOVATCHEV': '@andreykovatchev',
 'Agnieszka KOZŁOWSKA-RAJEWICZ': '@AKRajewicz',
 'Zdzisław KRASNODĘBSKI': '@ZdzKrasnodebski',
 'Constanze KREHL': '@ConstanzeKrehl',
 'Barbara KUDRYCKA': '@BarbaraKudrycka',
 'Werner KUHN': '@WernerKuhnMdEP',
 'Eduard Kukan': '@EduardKukan',
 'Miapetra KUMPULA-NATRI': '@miapetrakumpula',
 'Kostadinka KUNEVA': '@kkuneva',
 'Zbigniew KUŹMIUK': '@ZbigniewKuzmiuk',
 'Cécile Kashetu KYENGE': '@ckyenge',
 'Merja KYLLÖNEN': '@KyllonenMerja',
 'Miltiadis KYRKOS': '@miltos_kyrkos',
 'Georgios KYRTSOS': '@GiorgosKyrtsos',
 'Ilhan KYUCHYUK': '@ilhankyuchyuk',
 'Alain LAMASSOURE': '@ALamassoure',
 'Jean LAMBERT': '@GreenJeanMEP',
 'Philippe LAMBERTS': '@ph_lamberts',
 'Alexander Graf LAMBSDORFF': '@Lambsdorff',
 'Bernd LANGE': '@berndlange',
 'Esther de LANGE': '@Esther_de_Lange',
 'Werner LANGEN': '@langen_werner',
 'Marju LAURISTIN': '@LauristinMarju',
 'Giovanni LA VIA': '@giovannilavia',
 'Jérôme LAVRILLEUX': '@jlavrilleux',
 'Gilles LEBRETON': '@Gilles_Lebreton',
 'Constance LE GRIP': '@ConstanceLeGrip',
 'Ryszard Antoni LEGUTKO': '@RyszardLegutko',
 'Patrick LE HYARIC': '@PatrickLeHyaric',
 'Jo LEINEN': '@jo_leinen',
 'Jeroen LENAERS': '@jeroen_lenaers',
 'Jean-Marie LE PEN': '@lepenjm',
 'Janusz LEWANDOWSKI': '@J_Lewandowski',
 'Andrew LEWER': '@ALewerMBE',
 'Bogusław LIBERADZKI': '@BLiberadzki',
 'Peter LIESE': '@peterliese',
 'Arne LIETZ': '@ArneLietz',
 'Barbara LOCHBIHLER': '@blochbihler',
 'Philippe LOISEAU': '@ph_loiseau',
 'Morten LØKKEGAARD': '@Loekkegaard_MEP',
 'Sander LOONES': '@SanderLoones',
 'Javi LÓPEZ': '@fjavilopez',
 'Juan Fernando LÓPEZ AGUILAR': '@JFLopezAguilar',
 'Paloma LÓPEZ BERMEJO': '@palomalopezB',
 'Antonio LÓPEZ ISTÚRIZ WHITE': '@TonoEPP',
 'Sabine LÖSING': '@sabineverheyen',
 'Bernd LUCKE': '@BerndLucke',
 'Olle LUDVIGSSON': '@olleludvigsson',
 'Elżbieta Katarzyna ŁUKACIJEWSKA': '@lukacijewska',
 'Ulrike LUNACEK': '@UlrikeLunacek',
 'Krystyna ŁYBACKA': '@KrystynaLybacka',
 'David McALLISTER': '@davidmcallister',
 'Linda McAVAN': '@LindaMcAvanMEP',
 'Emma McCLARKIN': '@EmmaMcClarkin',
 'Mairead McGUINNESS': '@MaireadMcGMEP',
 'Petr MACH': '@PetrMachMEP',
 'Anthea McINTYRE': '@anthea_mcintyre',
 'Monica MACOVEI': '@MonicaMacovei1',
 'Ivana MALETIĆ': '@MaleticIvana',
 'Curzio MALTESE': '@curziomaltesetw',
 'Florent MARCELLESI': '@fmarcellesi',
 'Marian-Jean MARINESCU': '@MarianMarinescu',
 'David MARTIN': '@davidmartinmep',
 'Edouard MARTIN': '@edouardmartinEU',
 'Fulvio MARTUSCIELLO': '@fulviomartuscie',
 'Barbara MATERA': '@materabarbara',
 'Marisa MATIAS': '@mmatias_',
 'Gabriel MATO': '@GabrielMatoA',
 'Emmanuel MAUREL': '@emmanuelmaurel',
 'Eva MAYDELL': '@EvaMaydell',
 'Alex MAYER': '@alexlmayer',
 'Gesine MEISSNER': '@gesine_meissner',
 'Tamás MESZERICS': '@MeszericsT',
 'Roberta METSOLA': '@RobertaMetsola',
 'Louis MICHEL': '@louismichelMR',
 'Martina MICHELS': '@martina_michels',
 'Miroslav MIKOLÁŠIK': '@miromikolasik',
 'Francisco José MILLÁN MON': '@ppegrupo',
 'Matthijs van MILTENBURG': '@MatthijsvMilt',
 'Anne-Marie MINEUR': '@AnneMarieMineur',
 'Marlene MIZZI': '@MarleneMizzi',
 'Sorin MOISĂ': '@sorinmoisa',
 'Cláudia MONTEIRO DE AGUIAR': '@cmonteiroaguiar',
 'Clare MOODY': '@ClareMoodyMEP',
 'Claude MORAES': '@ClaudeMoraesMEP',
 'Nadine MORANO': '@nadine__morano',
 'Elisabeth MORIN-CHARTIER': '@emorinchartier',
 'Alessia Maria MOSCA': '@alessiamosca',
 'Siegfried MUREŞAN': '@SMuresan',
 'Renaud MUSELIER': '@RenaudMuselier',
 'Alessandra MUSSOLINI': '@Ale_Mussolini_',
 'Victor NEGRESCU': '@negrescuvictor',
 'Momchil NEKOV': '@MomchilNekov',
 'Angelika NIEBLER': '@ANiebler',
 'Luděk NIEDERMAYER': '@LudekNie',
 'Péter NIEDERMÜLLER': '@NiedermullerMEP',
 'Jens NILSSON': '@jensni',
 'Liadh NÍ RIADA': '@LiadhNiRiadaMEP',
 'Andrey NOVAKOV': '@AndreyNovakov',
 'Jan OLBRYCHT': '@JanOlbrycht',
 'Younous OMARJEE': '@younousomarjee',
 'Artis PABRIKS': '@Pabriks',
 'Pier Antonio PANZERI': '@AntonioPanzeri',
 'Massimo PAOLUCCI': '@MassimoPaolucc6',
 'Demetris PAPADAKIS': '@DemPapadakis',
 'Dimitrios PAPADIMOULIS': '@papadimoulis',
 'Gilles PARGNEAUX': '@gillespargneaux',
 'Margot PARKER': '@MargotLJParker',
 'Ioan Mircea PAŞCU': '@ioanmirceapascu',
 'Aldo PATRICIELLO': '@PatricielloAldo',
 'Emilian PAVEL': '@PavelEmilian',
 'Piernicola PEDICINI': '@PediciniM5S',
 'Vincent PEILLON': '@Vincent_Peillon',
 'Alojz PETERLE': '@lojzepeterle',
 'Florian PHILIPPOT': '@f_philippot',
 'Pina PICIERNO': '@pinapic',
 'Tonino PICULA': '@TPicula',
 'Markus PIEPER': '@markuspieperMEP',
 'Sirpa PIETIKÄINEN': '@spietikainen',
 'Kati PIRI': '@KatiPiri',
 'Gianni PITTELLA': '@giannipittella',
 'Pavel POC': '@pavelpoc',
 'Stanislav POLČÁK': '@stanislavpolcak',
 'Maurice PONGA': '@mauriceponga',
 'Jiří POSPÍŠIL': '@Pospisil_Jiri',
 'Soraya POST': '@SorayaPostFi',
 'Cristian Dan PREDA': '@CDPreda',
 'Gabriele PREUSS': '@GabrielePreuss',
 'Franck PROUST': '@franckproust',
 'Carolina PUNSET': '@carolinapunset',
 'Emil RADEV': '@Emil_Radev',
 'Julia REDA': '@Senficon',
 'Viviane REDING': '@VivianeRedingEU',
 'Evelyn REGNER': '@Evelyn_Regner',
 'Michel REIMON': '@michelreimon',
 'Terry REINTKE': '@TerryReintke',
 'Herbert REUL': '@hreul',
 "Christine REVAULT D'ALLONNES BONNEFOY": '@cdallonnes',
 'Frédérique RIES': '@Frederiqueries',
 'Michèle RIVASI': '@MicheleRivasi',
 'Robert ROCHEFORT': '@robertrochefort',
 'Liliana RODRIGUES': '@LilianaMEP',
 'Inmaculada RODRÍGUEZ PIÑERO FERNÁNDEZ': '@RodriguezPinero',
 'Ulrike RODUST': '@UlrikeRodust',
 'Jens ROHDE': '@rohde_jens',
 'Claude ROLIN': '@clauderolin',
 'Dariusz ROSATI': '@DariuszRosati',
 'Virginie ROZIÈRE': '@VRoziere',
 'Paul RÜBIG': '@PaulRuebig',
 'Tokia SAÏFI': '@TokiaSaifi',
 'Massimiliano SALINI': '@MaxSalini',
 'Lola SÁNCHEZ CALDENTEY': '@LolaPodemos',
 'Anne SANDER': '@ASanderMEP',
 'Alfred SANT': '@SantAlfred',
 'Daciana Octavia SÂRBU': '@DacianaSarbu',
 'Judith SARGENTINI': '@judithineuropa',
 'Petri SARVAMAA': '@petrisarvamaa',
 'Jacek SARYUSZ-WOLSKI': '@JSaryuszWolski',
 'David-Maria SASSOLI': '@DavidSassoli',
 'Algirdas SAUDARGAS': '@Saudargas',
 'Marietje SCHAAKE': '@MarietjeSchaake',
 'Christel SCHALDEMOSE': '@SchaldemoseMEP',
 'Elly SCHLEIN': '@ellyesse',
 'Claudia SCHMIDT': '@Schmidt_Clau',
 'György SCHÖPFLIN': '@schopflinMEP',
 'Annie SCHREIJER-PIERIK': '@AnnieSchreijer',
 'Sven SCHULZE': '@schulzeeuropa',
 'Andreas SCHWAB': '@Andreas_Schwab',
 'Olga SEHNALOVÁ': '@OlgaSehnalova',
 'Maria Lidia SENRA RODRÍGUEZ': '@LidiaSenra',
 'Remo SERNAGIOTTO': '@SernagiottoRemo',
 'Jill SEYMOUR': '@JSeymourUKIP',
 'Czesław Adam SIEKIERSKI': '@CzSiekierski',
 'Peter SIMON': '@PeterSimonMEP',
 'Siôn SIMON': '@sionsimon',
 'Birgit SIPPEL': '@BirgitSippelMEP',
 'Davor ŠKRLEC': '@DavorSkrlec',
 'Alyn SMITH': '@AlynSmithMEP',
 'Michaela ŠOJDROVÁ': '@msojdrova',
 'Igor ŠOLTES': '@isoltesEP',
 'Martin SONNEBORN': '@MartinSonneborn',
 'Renato SORU': '@renatosoru',
 'Maria SPYRAKI': '@MariaSpyraki',
 'Bart STAES': '@BartStaes',
 'Sergei STANISHEV': '@SergeiStanishev',
 'Ivan ŠTEFANEC': '@IvanStefanec',
 'Jutta STEINRUCK': '@JuttaSteinruck',
 'Jaromír ŠTĚTINA': '@StetinaEP',
 'Helga STEVENS': '@StevensHelga',
 'Catherine STIHLER': '@C_Stihler_MEP',
 'Theodor Dumitru STOLOJAN': '@TheodorStolojan',
 'Dubravka ŠUICA': '@dubravkasuica',
 'Patricija ŠULIN': '@PatricijaSulin',
 'Pavel SVOBODA': '@1PavelSvoboda',
 'Neoklis SYLIKIOTIS': '@sylikiotis',
 'Eleftherios SYNADINOS': '@Synadinos_Eleft',
 'Tibor SZANYI': '@szanyitibor',
 'Adam SZEJNFELD': '@szejnfeld',
 'Antonio TAJANI': '@Antonio_Tajani',
 'Paul TANG': '@paultang',
 'Claudia ȚAPARDEL': '@ClaudiaTapardel',
 'Marc TARABELLA': '@marctarabella',
 'Indrek TARAND': '@indrektarand',
 'Keith TAYLOR': '@GreenKeithMEP',
 'Pavel TELIČKA': '@Telicka',
 'Josep-Maria TERRICABRAS': '@jmterricabras',
 'Eleni THEOCHAROUS': '@THEOCHAROUSE',
 'Isabelle THOMAS': '@Isabel_thomasEU',
 'Róża Gräfin von THUN UND HOHENSTEIN': '@rozathun',
 'Patrizia TOIA': '@toiapatrizia',
 'Ruža TOMAŠIĆ': '@RuzaTomasic',
 'Romana TOMC': '@RomanaTomc',
 'Helga TRÜPEL': '@HelgaTruepel',
 'Claude TURMES': '@ClaudeTurmes',
 'Marita ULVSKOG': '@maritaulvskog',
 'Traian UNGUREANU': '@TraianUngureanu',
 'Miguel URBÁN CRESPO': '@MiguelUrban',
 'Ernest URTASUN': '@ernesturtasun',
 'Viktor USPASKICH': '@ViktorUspaskich',
 'Inese VAIDERE': '@IneseVaidere',
 'Adina-Ioana VĂLEAN': '@AdinaValean',
 'Elena VALENCIANO': '@ElenaValenciano',
 'Bodil VALERO': '@bodilvalero',
 'Ángela VALLINA': '@AngelaVallina',
 'Monika VANA': '@MonikaVana',
 'Kathleen VAN BREMPT': '@kvanbrempt',
 'Tom VANDENKENDELAERE': '@tomvdkendelaere',
 'Derek VAUGHAN': '@derekvaughan',
 'Paavo VÄYRYNEN': '@kokokansanpaavo',
 'Marie-Christine VERGIAT': '@MCVergiat',
 'Sabine VERHEYEN': '@sabineverheyen',
 'Guy VERHOFSTADT': '@GuyVerhofstadt',
 'Daniele VIOTTI': '@danieleviotti',
 'Henna VIRKKUNEN': '@HennaVirkkunen',
 'Axel VOSS': '@AxelVossMdEP',
 'Elissavet VOZEMBERG-VRIONIDI': '@vozemberg',
 'Jarosław WAŁĘSA': '@WalesaMEP',
 'Julie WARD': '@julie4nw',
 'Manfred WEBER': '@ManfredWeber',
 'Renate WEBER': '@renateweber',
 'Josef WEIDENHOLZER': '@Weidenholzer',
 'Kerstin WESTPHAL': '@WestphalKerstin',
 'Dame Glenis WILLMOTT': '@GlenisWillmott',
 'Boris ZALA': '@zalaboris',
 'Marco ZANNI': '@Marcozanni86',
 'Flavio ZANONATO': '@flaviozanonato',
 'Tatjana ŽDANOKA': '@Tatjana_Zdanoka',
 'Tomáš ZDECHOVSKÝ': '@TomZdechovsky',
 'Bogdan Andrzej ZDROJEWSKI': '@BZdrojewski',
 'Joachim ZELLER': '@joachimzeller',
 'Roberts ZĪLE': '@robertszile',
 'Gabriele ZIMMER': '@GabiZimmerMEP',
 'Carlos ZORRINHO': '@czorrinho',
 'Željana ZOVKO': '@ZovkoEU',
 'Milan ZVER': '@MilanZver',
 'Tadeusz ZWIEFKA': '@TadeuszZwiefka'};

function getRandomSubarray(arr, size) {
    var shuffled = arr.slice(0), i = arr.length, temp, index;
    while (i--) {
        index = Math.floor((i + 1) * Math.random());
        temp = shuffled[index];
        shuffled[index] = shuffled[i];
        shuffled[i] = temp;
    }
    return shuffled.slice(0, size);
}

var text_max = 140;

accounts = Object.values(mep);
$('#text').val(getRandomSubarray(accounts, 3).join(' '));
$('#count_message').html(text_max-$('#text').val().length + ' characters left');
$('#cntlabel').text('Number of accounts to fetch from ' + accounts.length + ' MEPs: ');

$('#text').keyup(function() {
  var text_length = $('#text').val().length;
  var text_remaining = text_max - text_length;

  $('#count_message').html(text_remaining + ' characters left');
});

$('#shuffle').click(function() {
  $('#text').val(getRandomSubarray(accounts, $('#cnt').val()).join(' '));
  $('#count_message').html(text_max-$('#text').val().length + ' characters left');
})
